---

- name: allow Logstash opening of privileged ports
  shell: "setcap 'cap_net_bind_service=+ep' $(readlink -f /usr/bin/java)"
  changed_when: false
- name: Find libjli library
  shell: 'set -o pipefail && find / -name libjli.so -exec dirname {} \; | head -1'
  changed_when: false
  register: libjli_path
- name: Enable ldconfig to search for libjli
  template:
    src: java-libjli.conf.j2
    dest: /etc/ld.so.conf.d/java-libjli.conf
    owner: root
    group: root
    mode: 0444
  notify:
    - call ldconfig
