---
# handlers file for logstash
- name: Restart Logstash
  service:
    name: logstash
    state: restarted
- name: Restart Logstash noauto
  service:
    name: logstash
    state: restarted
  when: not logstash_config_autoreload
- name: call ldconfig
  command: "/sbin/ldconfig"
